(() => {
  'use strict';
  const KEY = 'lifeos.v9.complete';
  const OLD_KEYS = ['lifeos.v8.rings','lifeos.v7.design','lifeos.v6.visual','lifeos.v5.config','lifeos.state'];
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const pad = n => String(n).padStart(2,'0');
  const todayISO = () => new Date().toISOString().slice(0,10);
  const uid = () => Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-5);
  const esc = s => String(s ?? '').replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const min = t => { const [h,m]=String(t||'00:00').split(':').map(Number); return (h||0)*60+(m||0); };
  const hhmm = m => `${pad(Math.floor(Math.max(0,m)/60))}:${pad(Math.max(0,m)%60)}`;
  const dur = m => { m=Math.max(0,Math.round(m)); const h=Math.floor(m/60), mm=m%60; return h ? `${h}ч${mm?` ${mm}м`:''}` : `${mm}м`; };
  const pct = (a,b) => b>0 ? Math.max(0,Math.min(100,Math.round(a/b*100))) : 0;
  const clamp = (n,a,b)=>Math.max(a,Math.min(b,n));
  const dateObj = iso => { const [y,m,d]=iso.split('-').map(Number); return new Date(y,m-1,d); };
  const addDays = (iso, n) => { const d=dateObj(iso); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
  const ruDate = iso => new Intl.DateTimeFormat('ru-RU',{weekday:'short', day:'numeric', month:'long', year:'numeric'}).format(dateObj(iso));
  const shortDate = iso => new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(dateObj(iso));
  const dayKey = iso => ['sun','mon','tue','wed','thu','fri','sat'][dateObj(iso).getDay()];
  const weekBounds = iso => { const d=dateObj(iso); const day=(d.getDay()+6)%7; const start=addDays(iso,-day); return {start,end:addDays(start,6)}; };
  const allDates = (start,end) => { const a=[]; for(let d=start; d<=end; d=addDays(d,1)) a.push(d); return a; };
  const THEMES = [
    ['system','Системная','#18223d','#7c5cff'],['light','iOS Light','#f7f9ff','#71c7ff'],['dark','iOS Dark','#050813','#0a84ff'],['midnight','Midnight','#050816','#7c5cff'],['aurora','Aurora','#07121d','#58ffcb'],['fitness','Apple Fitness','#070b11','#a3ff12'],['music','Apple Music','#0c0610','#ff2d55'],['journal','Apple Journal','#15120f','#d6a55b'],['ios7','iOS 7 Frost','#7ac8ff','#f8a1d1'],['ios13','iOS 13','#000000','#0a84ff'],['ios17','iOS 17 Pro','#080b16','#5e5ce6'],['ios18','iOS 18 Liquid','#070a16','#9b7cff'],['aqua','Classic Aqua','#42bfff','#0b65b5'],['graphite','Graphite','#11151d','#a5adba'],['ipod','iPod','#0b0b0d','#d1d1d6'],['snitch','Стукач','#100a05','#ffd60a']
  ];
  const DAYS = [['mon','Пн'],['tue','Вт'],['wed','Ср'],['thu','Чт'],['fri','Пт'],['sat','Сб'],['sun','Вс']];
  const DEFAULT_SCHEDULE = { mon:{enabled:true,start:'10:00',end:'17:00'}, tue:{enabled:true,start:'10:00',end:'17:00'}, wed:{enabled:true,start:'10:00',end:'17:00'}, thu:{enabled:true,start:'10:00',end:'17:00'}, fri:{enabled:true,start:'10:00',end:'17:00'}, sat:{enabled:true,start:'10:00',end:'14:00'}, sun:{enabled:false,start:'10:00',end:'14:00'} };
  const DEFAULT_WIDGETS = {hero:true,rings:true,weekly:true,planner:true,quick:true,timeline:true,insights:true,evening:true};
  const FOCUS_MODES = [{id:'25',label:'25/5',minutes:25},{id:'50',label:'50/10',minutes:50},{id:'90',label:'90/20',minutes:90},{id:'custom',label:'Свой 30',minutes:30}];
  const store = (() => {
    let mem = {};
    const test = s => { try { const k='lifeos.test'; s.setItem(k,'1'); s.removeItem(k); return true; } catch { return false; } };
    if(test(localStorage)) return localStorage;
    if(test(sessionStorage)) return sessionStorage;
    return { getItem:k=>mem[k]||null, setItem:(k,v)=>{mem[k]=String(v)}, removeItem:k=>delete mem[k] };
  })();
  let state;
  let activeTab = 'dashboard';
  let focus = {mode:FOCUS_MODES[0], remaining:25*60, running:false, startedAt:null, interval:null};

  function defaults(){
    return {
      version:9, configured:false, activeDate: todayISO(), theme:'system', glassOpacity:68, glassBlur:20, animationLevel:'normal',
      config:{startDate:'2026-07-03', endDate:'2026-08-31', sportWeeklyTarget:3, selfDailyTarget:60, schedule: JSON.parse(JSON.stringify(DEFAULT_SCHEDULE))},
      categories:[
        {id:'work', name:'Работа', type:'work', icon:'💼', color:'#ff2d55', dailyTarget:0, weeklyTarget:0, unit:'мин'},
        {id:'sport', name:'Спорт', type:'sport', icon:'🏃', color:'#a3ff12', dailyTarget:1, weeklyTarget:3, unit:'трен.'},
        {id:'self', name:'Саморазвитие', type:'self', icon:'📚', color:'#30d5ff', dailyTarget:60, weeklyTarget:420, unit:'мин'},
        {id:'rest', name:'Отдых', type:'custom', icon:'☕', color:'#ffd60a', dailyTarget:0, weeklyTarget:0, unit:'мин'},
        {id:'other', name:'Другое', type:'custom', icon:'✨', color:'#bf5af2', dailyTarget:0, weeklyTarget:0, unit:'мин'}
      ],
      ringSlots:['work','sport','self'], widgets:{...DEFAULT_WIDGETS}, entries:[], dayPlans:{}, moods:{}, goals:[], projects:[], templates:[], habits:[], finance:{rate:0,bonus:0,penalty:0,target:0}
    };
  }
  function migrateOld(raw){
    const base = defaults();
    if(!raw) return base;
    try{
      const old = JSON.parse(raw);
      if(old.entries) base.entries = old.entries.map(e=>({id:e.id||uid(), date:e.date||todayISO(), start:e.start||'10:00', end:e.end||'10:30', categoryId: inferCat(e), title:e.selfdevActivity||e.sportActivity||e.type||'', note:e.note||'', intensity:e.intensity||'', calories:Number(e.calories||0), source:e.auto?'auto':'migrated'}));
      if(old.workConfig){ base.config.startDate=old.workConfig.startDate||base.config.startDate; base.config.endDate=old.workConfig.endDate||base.config.endDate; base.config.sportWeeklyTarget=Number(old.workConfig.targetWorkoutsPerWeek||base.config.sportWeeklyTarget); if(old.workConfig.schedule) base.config.schedule = {...base.config.schedule, ...old.workConfig.schedule}; }
      if(old.theme) base.theme=old.theme;
      if(old.glassOpacity) base.glassOpacity=old.glassOpacity;
      if(old.glassBlur) base.glassBlur=old.glassBlur;
      if(old.animationLevel) base.animationLevel=old.animationLevel;
      if(old.goals) base.goals=old.goals;
      if(old.projects) base.projects=old.projects;
      if(old.moods || old.daily) base.moods=old.moods||old.daily||{};
      base.configured = Boolean(old.configured || old.hasSetup || old.workConfig);
      return base;
    }catch{return base}
  }
  function inferCat(e){ const t=String(e.type||'').toLowerCase(); if(t.includes('работ')) return 'work'; if(t.includes('спорт')||e.sportActivity) return 'sport'; if(t.includes('само')||t.includes('уч')||e.selfdevActivity) return 'self'; return 'other'; }
  function load(){
    const raw = store.getItem(KEY);
    if(raw){ try{ return {...defaults(), ...JSON.parse(raw)}; } catch{} }
    for(const k of OLD_KEYS){ const r=store.getItem(k); if(r) return migrateOld(r); }
    return defaults();
  }
  function save(){ store.setItem(KEY, JSON.stringify(state)); }
  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(t._timer); t._timer=setTimeout(()=>t.classList.remove('show'),2400); }
  function category(id){ return state.categories.find(c=>c.id===id) || state.categories[0]; }
  function categoriesByType(type){ return state.categories.filter(c=> type==='all' || c.type===type || c.id===type); }
  function entryMins(e){ let s=min(e.start), en=min(e.end); if(en<s) en+=1440; return Math.max(0,en-s); }
  function entriesFor(date){ return state.entries.filter(e=>e.date===date).sort((a,b)=>min(a.start)-min(b.start)); }
  function entriesByType(date,type){ return entriesFor(date).filter(e=>category(e.categoryId).type===type || e.categoryId===type); }
  function sum(date, type){ return entriesByType(date,type).reduce((a,e)=>a+entryMins(e),0); }
  function sportSessions(date){ return entriesByType(date,'sport').length; }
  function planFor(date){ const s=state.config.schedule[dayKey(date)] || DEFAULT_SCHEDULE[dayKey(date)]; if(!s.enabled) return {enabled:false,start:s.start,end:s.end,minutes:0,label:'Выходной'}; const minutes=Math.max(0,min(s.end)-min(s.start)); return {enabled:true,start:s.start,end:s.end,minutes,label:`${DAYS.find(d=>d[0]===dayKey(date))?.[1]||''} ${s.start}–${s.end}`}; }
  function weekDates(date){ const b=weekBounds(date); return allDates(b.start,b.end); }
  function workPlanPeriod(){ return allDates(state.config.startDate,state.config.endDate).reduce((a,d)=>a+planFor(d).minutes,0); }
  function workFactPeriod(){ return state.entries.filter(e=>category(e.categoryId).type==='work' && e.date>=state.config.startDate && e.date<=state.config.endDate).reduce((a,e)=>a+entryMins(e),0); }
  function metricDaily(catId,date=state.activeDate){ const c=category(catId); const p=planFor(date); if(catId==='work'||c.type==='work') return {value:sum(date,'work'), target:p.minutes, unit:'мин', percent:p.minutes?pct(sum(date,'work'),p.minutes):(sum(date,'work')?100:0)};
    if(catId==='sport'||c.type==='sport') return {value:sportSessions(date), target:Math.max(1,c.dailyTarget||1), unit:'трен.', percent:pct(sportSessions(date),Math.max(1,c.dailyTarget||1))};
    const value=sum(date, c.type==='self'?'self':catId); const target=Number(c.dailyTarget || (c.type==='self'?state.config.selfDailyTarget:60)); return {value,target,unit:c.unit||'мин',percent:target?pct(value,target):(value?100:0)};
  }
  function metricWeekly(catId,date=state.activeDate){ const c=category(catId), days=weekDates(date); if(catId==='work'||c.type==='work'){ const target=days.reduce((a,d)=>a+planFor(d).minutes,0), value=days.reduce((a,d)=>a+sum(d,'work'),0); return {value,target,unit:'мин',percent:pct(value,target)}; }
    if(catId==='sport'||c.type==='sport'){ const value=days.reduce((a,d)=>a+sportSessions(d),0), target=Number(state.config.sportWeeklyTarget||c.weeklyTarget||3); return {value,target,unit:'трен.',percent:pct(value,target)}; }
    const value=days.reduce((a,d)=>a+sum(d,c.type==='self'?'self':catId),0), target=Number(c.weeklyTarget||((c.dailyTarget||state.config.selfDailyTarget)*7)); return {value,target,unit:c.unit||'мин',percent:pct(value,target)};
  }
  function applyTheme(){
    const theme = state.theme==='system' ? (matchMedia('(prefers-color-scheme: light)').matches?'light':'dark') : state.theme;
    document.body.dataset.theme = theme;
    document.body.classList.toggle('anim-low', state.animationLevel==='low');
    document.body.classList.toggle('anim-high', state.animationLevel==='high');
    document.documentElement.style.setProperty('--glass-opacity', Number(state.glassOpacity||68)/100);
    document.documentElement.style.setProperty('--glass-blur', `${state.glassBlur||20}px`);
  }
  function fillThemeSelect(sel){ if(!sel) return; sel.innerHTML = THEMES.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join(''); sel.value=state.theme; }
  function renderSchedule(containerId,prefix){ const el=$(containerId); if(!el) return; el.innerHTML=DAYS.map(([k,l])=>{ const s=state.config.schedule[k]||DEFAULT_SCHEDULE[k]; return `<div class="schedule-row"><label class="schedule-day"><input id="${prefix}-${k}-enabled" type="checkbox" ${s.enabled?'checked':''}><span>${l}</span></label><label class="field">Начало<input id="${prefix}-${k}-start" class="input" type="time" value="${s.start}" step="60"></label><label class="field">Конец<input id="${prefix}-${k}-end" class="input" type="time" value="${s.end}" step="60"></label></div>`; }).join(''); }
  function readSchedule(prefix){ const schedule={}; DAYS.forEach(([k])=>{ let start=$(`#${prefix}-${k}-start`)?.value||DEFAULT_SCHEDULE[k].start; let end=$(`#${prefix}-${k}-end`)?.value||DEFAULT_SCHEDULE[k].end; if(min(end)<=min(start)) end=start; schedule[k]={enabled:Boolean($(`#${prefix}-${k}-enabled`)?.checked),start,end}; }); return schedule; }
  function setTab(tab){ activeTab=tab; $$('.view').forEach(v=>v.classList.toggle('active',v.id===tab)); $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); window.scrollTo({top:0,behavior:'smooth'}); renderAll(); }
  function visibleWidget(name){ return state.widgets?.[name]!==false; }
  function applyWidgets(){ $$('[data-widget]').forEach(el=>el.classList.toggle('hidden', !visibleWidget(el.dataset.widget))); }
  function setActiveDate(date){ state.activeDate=date; save(); renderAll(); }
  function quickAdd(categoryId, minutes, title='', note='', options={}){ const start=options.start||hhmm(Math.max(0,min(new Date().toTimeString().slice(0,5))-minutes)); const end=options.end||new Date().toTimeString().slice(0,5); state.entries.push({id:uid(),date:state.activeDate,start,end,categoryId,title,note,intensity:options.intensity||'',calories:Number(options.calories||0),source:'quick'}); save(); toast('Запись добавлена'); renderAll(); }
  function completeWork(){ const p=planFor(state.activeDate); if(!p.minutes){toast('Сегодня выходной по графику'); return;} state.entries = state.entries.filter(e=>!(e.date===state.activeDate && e.source==='auto-work')); state.entries.push({id:uid(),date:state.activeDate,start:p.start,end:p.end,categoryId:'work',title:'Полный рабочий день',note:'Авто-зачёт плана',source:'auto-work'}); save(); toast('Рабочий план засчитан'); renderAll(); }
  function completeSport(){ quickAdd('sport',45,'Тренировка','Быстрая отметка спорта',{start:'19:00',end:'19:45',intensity:'средняя',calories:250}); }
  function completeSelf(){ quickAdd('self',state.config.selfDailyTarget||60,'Саморазвитие','Быстрая отметка развития',{start:'20:00',end:hhmm(20*60+Number(state.config.selfDailyTarget||60))}); }
  function renderTop(){
    $('#activeDate').value=state.activeDate; $('#todayTitle').textContent=ruDate(state.activeDate); const p=planFor(state.activeDate); $('#todaySubtitle').textContent = `${p.enabled?`Работа ${p.start}–${p.end}`:'Выходной'} · спорт ${state.config.sportWeeklyTarget}/нед · саморазвитие ${state.config.selfDailyTarget}м/день`;
    fillThemeSelect($('#themeTop')); fillThemeSelect($('#themeSelect'));
    $('#themeTop').value=state.theme; $('#themeSelect').value=state.theme;
  }
  function renderRings(){
    const slots=state.ringSlots.slice(0,3); const metrics=slots.map(id=>metricDaily(id)); const deg=metrics.map(m=>Math.min(360,Math.round(m.percent*3.6))); const root=$('#tripleRings'); root.style.setProperty('--r0',`${deg[0]||0}deg`); root.style.setProperty('--r1',`${deg[1]||0}deg`); root.style.setProperty('--r2',`${deg[2]||0}deg`); ['--work','--sport','--self'].forEach((v,i)=>root.style.setProperty(v,category(slots[i])?.color||['#ff2d55','#a3ff12','#30d5ff'][i])); const avg=Math.round(metrics.reduce((a,m)=>a+m.percent,0)/(metrics.length||1)); $('#ringsAverage').textContent=`${avg}%`;
    $('#ringsList').innerHTML=slots.map((id,i)=>{ const c=category(id), m=metrics[i]; const value = m.unit==='мин'?dur(m.value):m.value; const target = m.unit==='мин'?dur(m.target):m.target; return `<div class="ring-item"><div class="ring-top"><div class="ring-title"><span>${esc(c.icon)}</span><strong>${esc(c.name)}</strong></div><b>${m.percent}%</b></div><div class="mini-progress" style="--bar:${c.color}"><span style="width:${m.percent}%"></span></div><small class="muted">${value} / ${target} ${m.unit==='мин'?'':m.unit}</small></div>`; }).join('');
  }
  function renderWeekly(){ const b=weekBounds(state.activeDate); $('#weekLabel').textContent=`${shortDate(b.start)} — ${shortDate(b.end)}`; const slots=state.ringSlots.slice(0,3); $('#weeklyRings').innerHTML=slots.map(id=>{ const c=category(id), m=metricWeekly(id); const value=m.unit==='мин'?dur(m.value):m.value; const target=m.unit==='мин'?dur(m.target):m.target; return `<div class="weekly-item"><div class="ring-title"><span>${esc(c.icon)}</span><strong>${esc(c.name)}</strong></div><strong>${m.percent}%</strong><div class="mini-progress" style="--bar:${c.color}"><span style="width:${m.percent}%"></span></div><span>${value} / ${target} ${m.unit==='мин'?'':m.unit}</span></div>`; }).join(''); }
  function buildSmartPlan(date=state.activeDate){ const p=planFor(date); const blocks=[]; if(p.enabled){ blocks.push({time:`${p.start}–${hhmm(min(p.start)+Math.round(p.minutes*.45))}`,title:'Работа: глубокий блок',cat:'work'}); blocks.push({time:`${hhmm(min(p.start)+Math.round(p.minutes*.45))}–${hhmm(min(p.start)+Math.round(p.minutes*.45)+40)}`,title:'Перерыв / обед',cat:'rest'}); blocks.push({time:`${hhmm(min(p.start)+Math.round(p.minutes*.45)+40)}–${p.end}`,title:'Работа: закрыть задачи',cat:'work'}); } else blocks.push({time:'—',title:'Выходной по рабочему графику',cat:'rest'});
    const weekSport=metricWeekly('sport',date); if(weekSport.value<weekSport.target) blocks.push({time:'вечер',title:`Спорт: осталось ${weekSport.target-weekSport.value} трен. на неделю`,cat:'sport'});
    const selfToday=metricDaily('self',date); if(selfToday.value<selfToday.target) blocks.push({time:'вечер',title:`Саморазвитие: ${dur(selfToday.target-selfToday.value)}`,cat:'self'});
    return blocks;
  }
  function renderPlanner(){ const accepted=state.dayPlans[state.activeDate]?.accepted; const blocks=state.dayPlans[state.activeDate]?.blocks || buildSmartPlan(); $('#smartPlan').innerHTML=blocks.map(b=>{ const c=category(b.cat)||category('other'); return `<div class="plan-item"><div><strong>${esc(b.time)}</strong><p class="muted">${esc(b.title)}</p></div><span class="pill" style="border-color:${c.color};color:${c.color}">${esc(c.icon)} ${esc(c.name)}</span></div>`; }).join(''); $('#acceptPlanBtn').textContent=accepted?'План принят':'Принять план'; }
  function renderQuick(){ const base=[{name:'Работа 1ч',cat:'work',min:60,icon:'💼'},{name:'Полный день',cat:'work',min:0,icon:'✅',fullWork:true},{name:'Тренировка 45м',cat:'sport',min:45,icon:'🏃'},{name:'Прогулка 30м',cat:'sport',min:30,icon:'🚶'},{name:'Книга 20м',cat:'self',min:20,icon:'📖'},{name:'Курс 40м',cat:'self',min:40,icon:'🎓'},{name:'Проект 1ч',cat:'self',min:60,icon:'💻'}]; const all=[...base,...state.templates]; $('#quickTemplates').innerHTML=all.map((t,i)=>`<button class="quick-card" data-quick="${i}" data-custom="${i>=base.length?1:0}"><strong>${esc(t.icon||category(t.cat)?.icon||'✨')} ${esc(t.name)}</strong><span class="muted">${t.fullWork?'по графику':dur(t.min||t.minutes||30)}</span></button>`).join(''); }
  function renderTimeline(){ const entries=entriesFor(state.activeDate); if(!entries.length){ $('#timeline').innerHTML='<div class="entry"><p class="muted">Записей пока нет. Добавь интервал или используй быстрый шаблон.</p></div>'; return;} $('#timeline').innerHTML=entries.map(e=>{ const c=category(e.categoryId); const w=clamp(entryMins(e)/480*100,8,100); return `<div class="time-block"><span class="muted">${esc(e.start)}</span><div class="time-bar" style="--c:${c.color};width:${w}%" title="${esc(c.name)}"></div><small class="muted">${esc(e.end)} · ${esc(c.icon)} ${esc(e.title||c.name)}</small></div>`; }).join(''); }
  function renderInsights(){ const p=planFor(state.activeDate), work=sum(state.activeDate,'work'), sport=metricWeekly('sport'), self=metricDaily('self'); const items=[]; if(p.enabled && work===0) items.push(['Рабочий день пустой',`План ${p.start}–${p.end}. Можно нажать «Работа» или добавить интервалы.`]); if(p.enabled && work>0 && work<p.minutes) items.push(['Не хватает работы',`Осталось ${dur(p.minutes-work)} до плана дня.`]); if(sport.value<sport.target) items.push(['Спорт недели',`Осталось ${sport.target-sport.value} тренировки до недельной цели.`]); if(self.value<self.target) items.push(['Саморазвитие',`Добей ещё ${dur(self.target-self.value)} сегодня.`]); if(!items.length) items.push(['День под контролем','Кольца закрываются нормально. Можно добавить заметку дня.']); $('#insights').innerHTML=items.map(x=>`<div class="entry"><strong>${esc(x[0])}</strong><p class="muted">${esc(x[1])}</p></div>`).join(''); }
  function renderEvening(){ const d=state.activeDate, p=planFor(d); const vals=[['Работа',dur(sum(d,'work')),p.minutes?dur(p.minutes):'выходной'],['Спорт',sportSessions(d),'трен.'],['Развитие',dur(sum(d,'self')),dur(state.config.selfDailyTarget)]]; $('#eveningReport').innerHTML=vals.map(v=>`<div class="metric"><strong>${esc(v[1])}</strong><span>${esc(v[0])} · ${esc(v[2])}</span></div>`).join(''); const mood=state.moods[d]||{}; $('#moodSelect').value=mood.mood||'🙂 Нормально'; $('#dayNote').value=mood.note||''; }
  function renderEntries(){ const list=entriesFor(state.activeDate); $('#dayEntries').innerHTML=list.length?list.map(e=>entryHtml(e)).join(''):'<div class="entry"><p class="muted">Записей пока нет.</p></div>'; }
  function entryHtml(e){ const c=category(e.categoryId); return `<article class="entry"><div class="entry-top"><div class="entry-title"><span>${esc(c.icon)}</span><strong>${esc(e.title||c.name)}</strong></div><span class="pill">${dur(entryMins(e))}</span></div><p class="muted">${esc(e.date)} · ${esc(e.start)}–${esc(e.end)} · ${esc(c.name)}${e.intensity&&e.intensity!=='—'?` · ${esc(e.intensity)}`:''}${e.calories?` · ${e.calories} ккал`:''}</p>${e.note?`<p>${esc(e.note)}</p>`:''}<div class="entry-actions"><button class="mini-btn" data-del-entry="${e.id}">Удалить</button><button class="mini-btn" data-copy-entry="${e.id}">Дубль</button></div></article>`; }
  function renderSport(){ const week=metricWeekly('sport'), today=sportSessions(state.activeDate), calories=state.entries.filter(e=>category(e.categoryId).type==='sport').reduce((a,e)=>a+Number(e.calories||0),0); $('#sportStats').innerHTML=[['Сегодня',today,'трен.'],['Неделя',`${week.value}/${week.target}`,'цель'],['Ккал',calories,'всего']].map(m=>`<div class="metric"><strong>${m[0]==='Ккал'?m[1]:m[1]}</strong><span>${m[0]} · ${m[2]}</span></div>`).join(''); const entries=state.entries.filter(e=>category(e.categoryId).type==='sport').sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30); $('#sportHistory').innerHTML=entries.length?entries.map(entryHtml).join(''):'<div class="entry"><p class="muted">Тренировок пока нет.</p></div>'; }
  function renderSelf(){ const today=sum(state.activeDate,'self'), week=metricWeekly('self'), total=state.entries.filter(e=>category(e.categoryId).type==='self').reduce((a,e)=>a+entryMins(e),0); $('#selfStats').innerHTML=[['Сегодня',dur(today),''],['Неделя',`${dur(week.value)} / ${dur(week.target)}`,''],['Всего',dur(total),'']].map(m=>`<div class="metric"><strong>${m[1]}</strong><span>${m[0]}</span></div>`).join(''); const entries=state.entries.filter(e=>category(e.categoryId).type==='self').sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30); $('#selfHistory').innerHTML=entries.length?entries.map(entryHtml).join(''):'<div class="entry"><p class="muted">Сессий саморазвития пока нет.</p></div>'; }
  function renderHistory(){ const dates=allDates(state.config.startDate,state.config.endDate).filter(d=>entriesFor(d).length || state.moods[d]).reverse(); $('#historyCards').innerHTML=dates.length?dates.slice(0,60).map(d=>{ const mood=state.moods[d]||{}; return `<article class="history-card"><div class="history-date"><strong>${ruDate(d)}</strong><span class="pill">${mood.closed?'закрыт':'открыт'}</span></div><div class="history-metrics"><div class="metric"><strong>${dur(sum(d,'work'))}</strong><span>работа</span></div><div class="metric"><strong>${sportSessions(d)}</strong><span>спорт</span></div><div class="metric"><strong>${dur(sum(d,'self'))}</strong><span>развитие</span></div></div>${mood.mood||mood.note?`<p class="muted">${esc(mood.mood||'')} ${esc(mood.note||'')}</p>`:''}</article>`; }).join(''):'<div class="entry"><p class="muted">История появится после первых записей.</p></div>'; }
  function renderAnalytics(){ const periodEntries=state.entries.filter(e=>e.date>=state.config.startDate&&e.date<=state.config.endDate); const total=periodEntries.reduce((a,e)=>a+entryMins(e),0); const by={}; periodEntries.forEach(e=>{ const c=category(e.categoryId); by[c.name]=(by[c.name]||{min:0,c}) ; by[c.name].min+=entryMins(e); }); $('#composition').innerHTML=Object.values(by).sort((a,b)=>b.min-a.min).map(x=>{ const p=total?pct(x.min,total):0; return `<div class="comp-row"><strong>${esc(x.c.icon)} ${esc(x.c.name)}</strong><div class="comp-bar"><span style="width:${p}%;--c:${x.c.color}"></span></div><span>${p}%</span></div>`; }).join('') || '<p class="muted">Пока нет данных.</p>'; const plan=workPlanPeriod(), fact=workFactPeriod(), left=Math.max(0,plan-fact); $('#periodStats').innerHTML=[['План',dur(plan),'работы'],['Факт',dur(fact),'работы'],['Осталось',dur(left),''],['Период',`${pct(fact,plan)}%`,'выполнено']].map(m=>`<div class="metric"><strong>${m[1]}</strong><span>${m[0]} ${m[2]}</span></div>`).join(''); const remDays=allDates(state.activeDate,state.config.endDate).filter(d=>planFor(d).minutes>0).length; $('#periodInsights').innerHTML=`<div class="entry"><strong>Антихаос</strong><p class="muted">${left?`Чтобы закрыть план, нужно в среднем ${dur(Math.ceil(left/Math.max(1,remDays)))} в каждый оставшийся рабочий день.`:'Рабочий план периода закрыт.'}</p></div>`; }
  function renderGoals(){ $('#goalsList').innerHTML=state.goals.length?state.goals.map(g=>{ const p=pct(Number(g.current),Number(g.target)); return `<div class="goal-card"><div class="ring-top"><strong>${esc(g.name)}</strong><span>${p}%</span></div><div class="mini-progress"><span style="width:${p}%"></span></div><p class="muted">${esc(g.current)} / ${esc(g.target)} ${esc(g.unit||'')}</p><div class="entry-actions"><button class="mini-btn" data-goal-inc="${g.id}">+1</button><button class="mini-btn" data-goal-del="${g.id}">Удалить</button></div></div>`; }).join(''):'<p class="muted">Целей пока нет.</p>'; }
  function renderProjects(){ $('#projectsList').innerHTML=state.projects.length?state.projects.map(p=>`<div class="goal-card"><div class="ring-top"><strong>${esc(p.name)}</strong><span>${p.progress}%</span></div><div class="mini-progress"><span style="width:${p.progress}%"></span></div><p class="muted">${esc(p.status)} ${p.url?`· ${esc(p.url)}`:''}</p>${p.note?`<p>${esc(p.note)}</p>`:''}<div class="entry-actions"><button class="mini-btn" data-project-del="${p.id}">Удалить</button></div></div>`).join(''):'<p class="muted">Проектов пока нет.</p>'; }
  function computeXP(){ const work=Math.floor(workFactPeriod()/30)*10, sport=state.entries.filter(e=>category(e.categoryId).type==='sport').length*35, self=Math.floor(state.entries.filter(e=>category(e.categoryId).type==='self').reduce((a,e)=>a+entryMins(e),0)/15)*10, days=Object.values(state.moods).filter(m=>m.closed).length*20; return work+sport+self+days; }
  function achievementData(){ const workH=Math.floor(workFactPeriod()/60), sportN=state.entries.filter(e=>category(e.categoryId).type==='sport').length, selfH=Math.floor(state.entries.filter(e=>category(e.categoryId).type==='self').reduce((a,e)=>a+entryMins(e),0)/60), closed=Object.values(state.moods).filter(m=>m.closed).length; const series=[['work','Работа','💼',workH,'ч'],['sport','Спорт','🏃',sportN,'трен.'],['self','Саморазвитие','📚',selfH,'ч'],['days','Закрытые дни','🌙',closed,'дн.']]; const thresholds=[1,3,5,10,15,25,50,75,100,150,250,500,750,1000]; return series.flatMap(s=>thresholds.map((t,i)=>({key:`${s[0]}-${t}`,title:`${s[1]} ${t} ${s[4]}`,icon:s[2],unlocked:s[3]>=t,tier:['бронза','серебро','золото','платина','ультра','легенда'][Math.min(5,Math.floor(i/2))],value:s[3],target:t}))); }
  function renderAchievements(){ const xp=computeXP(), level=Math.floor(xp/500)+1, next=500-(xp%500); $('#levelPill').textContent=`Lv.${level}`; $('#xpBox').innerHTML=`<h2>Lv.${level}</h2><p class="muted">XP: ${xp}. До следующего уровня: ${next} XP.</p><div class="mini-progress"><span style="width:${pct(xp%500,500)}%"></span></div>`; const data=achievementData(); $('#achievementsList').innerHTML=data.slice(0,80).map(a=>`<div class="badge ${a.unlocked?'':'locked'}"><div class="badge-icon">${a.unlocked?a.icon:'🔒'}</div><strong>${esc(a.title)}</strong><span class="muted">${esc(a.tier)} · ${a.value}/${a.target}</span></div>`).join(''); }
  function renderSettings(){
    $('#configStart').value=state.config.startDate; $('#configEnd').value=state.config.endDate; $('#configSportTarget').value=state.config.sportWeeklyTarget; $('#configSelfTarget').value=state.config.selfDailyTarget; renderSchedule('#configSchedule','config');
    $('#glassOpacity').value=state.glassOpacity; $('#glassBlur').value=state.glassBlur; $('#animationLevel').value=state.animationLevel; fillThemeSelect($('#themeSelect'));
    $('#themeList').innerHTML=THEMES.map(t=>`<button type="button" class="theme-tile ${state.theme===t[0]?'active':''}" data-theme-choice="${t[0]}" style="--a:${t[2]};--b:${t[3]}">${t[1]}</button>`).join('');
    const opts=state.categories.map(c=>`<option value="${c.id}">${c.icon} ${c.name}</option>`).join(''); ['ring0','ring1','ring2','tplCategory','entryCategory','focusCategory'].forEach(id=>{ const el=$('#'+id); if(el){ el.innerHTML=opts; }}); state.ringSlots.forEach((id,i)=>{ const el=$(`#ring${i}`); if(el) el.value=id; });
    $('#categoryList').innerHTML=state.categories.map(c=>`<span class="chip-card"><span>${esc(c.icon)} ${esc(c.name)}</span>${!['work','sport','self','rest','other'].includes(c.id)?`<button class="mini-btn" data-cat-del="${c.id}">×</button>`:''}</span>`).join('');
    $('#widgetSettings').innerHTML=Object.keys(DEFAULT_WIDGETS).map(k=>`<label><input type="checkbox" data-widget-toggle="${k}" ${visibleWidget(k)?'checked':''}> ${widgetName(k)}</label>`).join('');
    $('#templateList').innerHTML=state.templates.length?state.templates.map((t,i)=>`<span class="chip-card">${esc(t.icon||category(t.cat)?.icon||'✨')} ${esc(t.name)} · ${dur(t.minutes||t.min||30)} <button class="mini-btn" data-tpl-del="${i}">×</button></span>`).join(''):'<p class="muted">Своих шаблонов пока нет.</p>';
  }
  function widgetName(k){ return {hero:'Шапка дня',rings:'Кольца',weekly:'Неделя',planner:'Планировщик',quick:'Шаблоны',timeline:'Таймлайн',insights:'Антихаос',evening:'Вечерний отчёт'}[k]||k; }
  function renderSelects(){ const opts=state.categories.map(c=>`<option value="${c.id}">${c.icon} ${c.name}</option>`).join(''); ['entryCategory','focusCategory','tplCategory'].forEach(id=>{ const el=$('#'+id); if(el){ const old=el.value; el.innerHTML=opts; if(old) el.value=old; }}); }
  function renderAll(){ applyTheme(); applyWidgets(); renderTop(); renderSelects(); if($('#dashboard').classList.contains('active')||true){ renderRings(); renderWeekly(); renderPlanner(); renderQuick(); renderTimeline(); renderInsights(); renderEvening(); } renderEntries(); renderSport(); renderSelf(); renderHistory(); renderAnalytics(); renderGoals(); renderProjects(); renderAchievements(); if(activeTab==='settings') renderSettings(); }
  function acceptPlan(){ state.dayPlans[state.activeDate]={accepted:true,blocks:buildSmartPlan()}; save(); toast('План дня принят'); renderAll(); }
  function closeDay(){ const d=state.activeDate; state.moods[d]={...(state.moods[d]||{}), mood:$('#moodSelect').value, note:$('#dayNote').value.trim(), closed:true}; save(); toast('День закрыт'); renderAll(); }
  function exportJSON(){ download('lifeos-v9-backup.json', JSON.stringify(state,null,2), 'application/json;charset=utf-8'); }
  function download(name, data, type){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([data],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
  function buildReport(){ const plan=workPlanPeriod(), fact=workFactPeriod(), sport=state.entries.filter(e=>category(e.categoryId).type==='sport').length, self=state.entries.filter(e=>category(e.categoryId).type==='self').reduce((a,e)=>a+entryMins(e),0); const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><title>LifeOS Report</title><style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;margin:40px;line-height:1.5} .card{border:1px solid #ddd;border-radius:20px;padding:18px;margin:12px 0}</style><h1>LifeOS Report</h1><p>${state.config.startDate} — ${state.config.endDate}</p><div class="card"><h2>Итоги</h2><p>Работа: ${dur(fact)} / ${dur(plan)} (${pct(fact,plan)}%)</p><p>Спорт: ${sport} тренировок</p><p>Саморазвитие: ${dur(self)}</p><p>Уровень: ${Math.floor(computeXP()/500)+1}</p></div><div class="card"><h2>История</h2>${allDates(state.config.startDate,state.config.endDate).map(d=>`<p><b>${ruDate(d)}</b>: работа ${dur(sum(d,'work'))}, спорт ${sportSessions(d)}, развитие ${dur(sum(d,'self'))}</p>`).join('')}</div></html>`; return html; }
  function htmlReport(){ download('lifeos-report.html', buildReport(), 'text/html;charset=utf-8'); }
  function clearCache(){ if('serviceWorker' in navigator){ navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister()))).then(()=>caches?.keys?.()).then(keys=>Promise.all((keys||[]).map(k=>caches.delete(k)))).then(()=>toast('Кэш PWA сброшен. Перезагрузи приложение.')); } else toast('Service Worker недоступен'); }
  function bind(){
    $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab))); document.addEventListener('click',e=>{ const j=e.target.closest('[data-tab-jump]'); if(j) setTab(j.dataset.tabJump); });
    $('#activeDate').addEventListener('change',e=>setActiveDate(e.target.value)); $('#themeTop').addEventListener('change',e=>{state.theme=e.target.value; save(); renderAll();});
    $('#acceptPlanBtn').addEventListener('click',acceptPlan); $('#closeDayBtn').addEventListener('click',closeDay); $('#completeWorkBtn').addEventListener('click',completeWork); $('#completeSportBtn').addEventListener('click',completeSport); $('#completeSelfBtn').addEventListener('click',completeSelf); $('#backupTopBtn').addEventListener('click',exportJSON); $('#exportJson').addEventListener('click',exportJSON); $('#exportHtmlBtn').addEventListener('click',htmlReport);
    $('#dayNote').addEventListener('input',e=>{ const d=state.activeDate; state.moods[d]={...(state.moods[d]||{}),note:e.target.value}; save(); }); $('#moodSelect').addEventListener('change',e=>{ const d=state.activeDate; state.moods[d]={...(state.moods[d]||{}),mood:e.target.value}; save(); });
    $('#entryForm').addEventListener('submit',e=>{ e.preventDefault(); const entry={id:uid(),date:$('#entryDate').value,start:$('#entryStart').value,end:$('#entryEnd').value,categoryId:$('#entryCategory').value,title:$('#entryTitle').value.trim(),intensity:$('#entryIntensity').value,calories:Number($('#entryCalories').value||0),note:$('#entryNote').value.trim(),source:'manual'}; state.entries.push(entry); save(); e.target.reset(); $('#entryDate').value=state.activeDate; toast('Запись добавлена'); renderAll(); });
    document.addEventListener('click',e=>{ const d=e.target.dataset; if(d.quick!==undefined){ const base=[{name:'Работа 1ч',cat:'work',min:60},{name:'Полный день',cat:'work',fullWork:true},{name:'Тренировка 45м',cat:'sport',min:45},{name:'Прогулка 30м',cat:'sport',min:30},{name:'Книга 20м',cat:'self',min:20},{name:'Курс 40м',cat:'self',min:40},{name:'Проект 1ч',cat:'self',min:60}]; const all=[...base,...state.templates]; const t=all[Number(d.quick)]; if(t.fullWork) completeWork(); else quickAdd(t.cat||t.categoryId, Number(t.min||t.minutes||30), t.name, 'Быстрый шаблон'); }
      if(d.delEntry){ state.entries=state.entries.filter(x=>x.id!==d.delEntry); save(); renderAll(); }
      if(d.copyEntry){ const src=state.entries.find(x=>x.id===d.copyEntry); if(src){ state.entries.push({...src,id:uid(),date:state.activeDate,source:'copy'}); save(); renderAll(); toast('Запись продублирована'); }}
      if(d.goalInc){ const g=state.goals.find(x=>x.id===d.goalInc); if(g){ g.current=Number(g.current||0)+1; save(); renderAll(); }} if(d.goalDel){ state.goals=state.goals.filter(x=>x.id!==d.goalDel); save(); renderAll(); }
      if(d.projectDel){ state.projects=state.projects.filter(x=>x.id!==d.projectDel); save(); renderAll(); }
      if(d.catDel){ state.categories=state.categories.filter(x=>x.id!==d.catDel); state.ringSlots=state.ringSlots.map(id=>id===d.catDel?'other':id); save(); renderAll(); }
      if(d.tplDel!==undefined){ state.templates.splice(Number(d.tplDel),1); save(); renderAll(); }
      if(d.themeChoice){ state.theme=d.themeChoice; save(); renderAll(); }
    });
    $('#copyYesterdayBtn').addEventListener('click',()=>{ const y=addDays(state.activeDate,-1); const items=entriesFor(y); items.forEach(e=>state.entries.push({...e,id:uid(),date:state.activeDate,source:'copy-yesterday'})); save(); toast(`Скопировано: ${items.length}`); renderAll(); });
    $('#selfQuickForm').addEventListener('submit',e=>{ e.preventDefault(); const minutes=Number($('#selfMinutes').value||30); quickAdd('self',minutes,$('#selfTitle').value.trim()||$('#selfKind').value,$('#selfKind').value); e.target.reset(); $('#selfMinutes').value=30; });
    $('#goalForm').addEventListener('submit',e=>{ e.preventDefault(); state.goals.push({id:uid(),name:$('#goalName').value.trim(),current:Number($('#goalCurrent').value||0),target:Number($('#goalTarget').value||1),unit:$('#goalUnit').value.trim()}); save(); e.target.reset(); renderAll(); });
    $('#projectForm').addEventListener('submit',e=>{ e.preventDefault(); state.projects.push({id:uid(),name:$('#projectName').value.trim(),status:$('#projectStatus').value,progress:Number($('#projectProgress').value||0),url:$('#projectUrl').value.trim(),note:$('#projectNote').value.trim()}); save(); e.target.reset(); renderAll(); });
    $('#configForm').addEventListener('submit',e=>{ e.preventDefault(); state.config.startDate=$('#configStart').value; state.config.endDate=$('#configEnd').value; state.config.sportWeeklyTarget=Number($('#configSportTarget').value||3); state.config.selfDailyTarget=Number($('#configSelfTarget').value||60); state.config.schedule=readSchedule('config'); const self=category('self'); self.dailyTarget=state.config.selfDailyTarget; self.weeklyTarget=state.config.selfDailyTarget*7; const sport=category('sport'); sport.weeklyTarget=state.config.sportWeeklyTarget; state.configured=true; save(); toast('График сохранён'); renderAll(); });
    $('#configDefault').addEventListener('click',()=>{state.config={...state.config,startDate:'2026-07-03',endDate:'2026-08-31',sportWeeklyTarget:3,selfDailyTarget:60,schedule:JSON.parse(JSON.stringify(DEFAULT_SCHEDULE))}; save(); renderAll();});
    $('#visualForm').addEventListener('submit',e=>{ e.preventDefault(); state.theme=$('#themeSelect').value; state.glassOpacity=Number($('#glassOpacity').value); state.glassBlur=Number($('#glassBlur').value); state.animationLevel=$('#animationLevel').value; save(); toast('Визуал сохранён'); renderAll(); }); ['glassOpacity','glassBlur','animationLevel','themeSelect'].forEach(id=>$('#'+id)?.addEventListener('input',e=>{ if(id==='themeSelect') state.theme=e.target.value; else if(id==='animationLevel') state.animationLevel=e.target.value; else state[id]=Number(e.target.value); applyTheme(); }));
    $('#categoryForm').addEventListener('submit',e=>{ e.preventDefault(); const name=$('#catName').value.trim(); const id='cat-'+uid(); state.categories.push({id,name,type:$('#catType').value,icon:$('#catIcon').value.trim()||'✨',color:$('#catColor').value,dailyTarget:Number($('#catDaily').value||0),weeklyTarget:Number($('#catDaily').value||0)*7,unit:$('#catType').value==='sport'?'трен.':'мин'}); save(); e.target.reset(); $('#catColor').value='#7c5cff'; toast('Категория создана'); renderAll(); });
    $('#ringsForm').addEventListener('submit',e=>{ e.preventDefault(); state.ringSlots=[$('#ring0').value,$('#ring1').value,$('#ring2').value]; save(); toast('Кольца обновлены'); renderAll(); });
    $('#templateForm').addEventListener('submit',e=>{ e.preventDefault(); const cat=category($('#tplCategory').value); state.templates.push({name:$('#tplName').value.trim(),cat:cat.id,minutes:Number($('#tplMinutes').value||30),icon:cat.icon}); save(); e.target.reset(); renderAll(); });
    $('#widgetSettings').addEventListener('change',e=>{ if(e.target.dataset.widgetToggle){ state.widgets[e.target.dataset.widgetToggle]=e.target.checked; save(); renderAll(); }});
    $('#importJsonLabel').addEventListener('click',()=>$('#importJson').click()); $('#importJson').addEventListener('change',async e=>{ const f=e.target.files[0]; if(!f) return; try{ const data=JSON.parse(await f.text()); state={...defaults(),...data}; save(); toast('Импорт выполнен'); renderAll(); }catch{toast('Не удалось импортировать JSON');} });
    $('#clearCache').addEventListener('click',clearCache); $('#resetAll').addEventListener('click',()=>{ if(confirm('Удалить все данные LifeOS?')){ store.removeItem(KEY); state=defaults(); save(); location.reload(); }});
    $('#setupDefault').addEventListener('click',()=>{ state.config={...state.config,startDate:'2026-07-03',endDate:'2026-08-31',sportWeeklyTarget:3,selfDailyTarget:60,schedule:JSON.parse(JSON.stringify(DEFAULT_SCHEDULE))}; $('#setupStart').value=state.config.startDate; $('#setupEnd').value=state.config.endDate; $('#setupSportTarget').value=3; $('#setupSelfTarget').value=60; renderSchedule('#setupSchedule','setup'); });
    $('#setupForm').addEventListener('submit',e=>{ e.preventDefault(); state.config.startDate=$('#setupStart').value; state.config.endDate=$('#setupEnd').value; state.config.sportWeeklyTarget=Number($('#setupSportTarget').value||3); state.config.selfDailyTarget=Number($('#setupSelfTarget').value||60); state.config.schedule=readSchedule('setup'); state.configured=true; const self=category('self'); self.dailyTarget=state.config.selfDailyTarget; self.weeklyTarget=state.config.selfDailyTarget*7; const sport=category('sport'); sport.weeklyTarget=state.config.sportWeeklyTarget; save(); $('#onboarding').classList.add('hidden'); toast('LifeOS настроен'); renderAll(); });
    // Focus
    $('#focusModes').innerHTML=FOCUS_MODES.map((m,i)=>`<button class="soft-btn mode-btn ${i===0?'active':''}" data-focus-mode="${m.id}">${m.label}</button>`).join(''); $('#focusModes').addEventListener('click',e=>{ const b=e.target.closest('[data-focus-mode]'); if(!b) return; focus.mode=FOCUS_MODES.find(m=>m.id===b.dataset.focusMode)||FOCUS_MODES[0]; focus.remaining=focus.mode.minutes*60; $$('.mode-btn').forEach(x=>x.classList.toggle('active',x===b)); renderFocusClock(); });
    $('#focusStart').addEventListener('click',()=>{ if(focus.running) return; focus.running=true; focus.startedAt=Date.now(); focus.interval=setInterval(()=>{ focus.remaining--; if(focus.remaining<=0){ finishFocus(); } renderFocusClock(); },1000); });
    $('#focusPause').addEventListener('click',()=>{ focus.running=false; clearInterval(focus.interval); }); $('#focusStop').addEventListener('click',finishFocus);
    if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
    let deferred; window.addEventListener('beforeinstallprompt',e=>{ e.preventDefault(); deferred=e; $('#installBtn').hidden=false; }); $('#installBtn').addEventListener('click',async()=>{ if(deferred){ deferred.prompt(); deferred=null; $('#installBtn').hidden=true; }});
  }
  function renderFocusClock(){ $('#focusClock').textContent=`${pad(Math.floor(focus.remaining/60))}:${pad(focus.remaining%60)}`; }
  function finishFocus(){ if(focus.interval) clearInterval(focus.interval); if(focus.running || focus.remaining < focus.mode.minutes*60){ const done=Math.max(1,Math.round((focus.mode.minutes*60-focus.remaining)/60)); quickAdd($('#focusCategory').value||'self',done,$('#focusTitle').value.trim()||'Фокус-сессия','Автозапись из фокус-таймера'); } focus.running=false; focus.remaining=focus.mode.minutes*60; renderFocusClock(); }
  function init(){ state=load(); applyTheme(); bind(); $('#activeDate').value=state.activeDate; $('#entryDate').value=state.activeDate; $('#setupStart').value=state.config.startDate; $('#setupEnd').value=state.config.endDate; $('#setupSportTarget').value=state.config.sportWeeklyTarget; $('#setupSelfTarget').value=state.config.selfDailyTarget; renderSchedule('#setupSchedule','setup'); if(!state.configured) $('#onboarding').classList.remove('hidden'); renderFocusClock(); renderAll(); }
  document.addEventListener('DOMContentLoaded', init);
})();
